name: grpc_server
description: A simple command-line application.
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  async: ^2.4.1
  grpc: ^2.2.0
  protobuf: ^1.0.1

dev_dependencies:
  pedantic: ^1.9.0
  protoc_plugin: ^19.0.1